### ISSUE TITLE
Make icon sizable in template card

### ISSUE THREAD

**Issue by sotima** [piitaya/lovelace-mushroom-themes#13]
First of all: Thank you for your outstanding work on mushroom-cards. 

I would love to use them but encountered a small problem. I would like to be able to enlarge the icon size of (at least) the template card. Right now it seems to be fixed at 20px which for my eyes (I am 60 years young) on my phone is a bit small. I even tried to edit it in the mushroom.js (--mdc-icon-size in .shape ha-icon class) - but I can´t get it to work. So it would be much appreciated if you could make this size adjustable via a themes variable.

Thanks again! 

Matthias

**Comment by totalitarian** [comment]
I'd love this too

**Comment by redphx** [comment]
@sotima @totalitarian you should be able to change icon size with mushroom 1.8.1.
For example:
```yaml
Mushroom:
    mush-chip-icon-size: 0.6em
    mush-chip-font-size: 0.4em

    mush-icon-size: 54px
    
    modes:
        light: {}
        dark: {}
```
