### ISSUE TITLE
Mushroom Entity Card: Default color differs

### ISSUE THREAD

**Issue by pedolsky** [piitaya/lovelace-mushroom-themes#47]
It's stated that since 2022.11 Mushroom theme is not needed anymore. But without using it, the Mushroom Entity Card's default color doesn't respect HA's default state colors.

Example (2022.12.8):

![AAD3682B-BBD4-41AF-83C7-CA0AB899BC12](https://user-images.githubusercontent.com/71203830/209544378-d027ef86-2716-4755-83b8-2db547e20f82.jpeg)

```

      - type: custom:mushroom-entity-card
        entity: group.weihnachtsbeleuchtung
        name: mushroom-entity-card

      - type: tile
        entity: group.weihnachtsbeleuchtung
        name: tile

      - type: entities
        entities:
          - entity: group.weihnachtsbeleuchtung
            name: entities
        state_color: true

```
